[package]
name = "worsehttp"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]

[dependencies]
failure = "0.1"
httparse = "1"
log = "0.4"
net2 = "0.2"

[dev-dependencies]
pretty_env_logger = "0.2"

[profile.release]
lto = true